version: '3.8'

services:
  django_app:
    build: 
      context: .
      dockerfile: DockerfileLocal
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    # restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/pgg:/var/lib/postgresql
    user: "${UID}:${GID}"
    ports:
      - "5432:5432"